archive_a: Archives
archive_b: "Archives: %s"
blogroll: Blogroll
catalog: catalog
categories: Categories
category: Category
comment: Comments
date_format: YYYY/MM/DD
newer: Newer
next: Next
older: Older
over_the_wall: Loading comments box needs to over the wall
page: Page %d
powered_by: Powered by
prev: Prev
recent_posts: Recent Posts
rss_feed: RSS Feed
search: Search
share: Share
tag: Tag
tagcloud: Tag Cloud
tags: Tags
tweets: Tweets
untitled: Untitled
